# Site settings
title: Alessandro Cuzzocrea
email: your-email@domain.com
description: "Alessandro Cuzzocrea's personal homepage"
baseurl: ""
url: "http://www.alessandrocuzzocrea.com"
twitter_username: omar
github_username:  omar

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Japanisu
#defaults:
#  -
#    scope:
#      path: "ja" # an empty string here means all files in the project
#      type: "post"
#    values:
#      permalink: /ja/:year/:month/:day/:title/