baseURL = "https://alessandrocuzzocrea.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Alessandro Cuzzocrea"
enableRobotsTXT = true
enableGitInfo = true

disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[permalinks]
  posts = "/:slug/"

[params]
  author = "Alessandro Cuzzocrea"
  description = "Full-Stack Software Engineer"
  homePageDescription = "Full-Stack Software Engineer based in Tokyo"
  recentPosts = "Recent Posts"
  authorEmail = "YWxlc3NhbmRyby5jdXp6b2NyZWEyQGdtYWlsLmNvbQ=="
  authorGithub = "alessandrocuzzocrea"
  authorLinkedin = "alessandrocuzzocrea"

[languages]
  [languages.en]
    languageName = "English"
  [languages.ja]
    languageName = "Japanese"
    [languages.ja.params]
        description = "日本"
        homePageDescription = "フルスタックエンジニア"
        recentPosts = "新着記事"
