baseURL = "https://alessandrocuzzocrea.com/"
languageCode = "en-us"
title = "Alessandro Cuzzocrea - Full-Stack Software Engineer"
enableRobotsTXT = true

disableKinds = ["section"]

[permalinks]
  posts = "/:slug/"

[params]
  author = "Alessandro Cuzzocrea"
  description = "Full-Stack Software Engineer"
  authorEmail = "YWxlc3NhbmRyby5jdXp6b2NyZWEyQGdtYWlsLmNvbQ=="
  authorGithub = "alessandrocuzzocrea"
  authorLinkedin = "alessandrocuzzocrea"
