baseURL = "https://alessandrocuzzocrea.com/"
languageCode = "en-us"
title = "Alessandro Cuzzocrea"

disableKinds = ["section"]

[permalinks]
  posts = "/:slug/"

[params]
  author = "Alessandro Cuzzocrea"
  description = "Full-Stack Software Engineer"
